# Generated by Django 6.0.5 on 2026-05-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight_kg',
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
    ]
